/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class douzi_kaoshi_scpm_jni_DBManagerNative */

#ifndef _Included_douzi_kaoshi_scpm_jni_DBManagerNative
#define _Included_douzi_kaoshi_scpm_jni_DBManagerNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     douzi_kaoshi_scpm_jni_DBManagerNative
 * Method:    open_db
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_douzi_kaoshi_scpm_jni_DBManagerNative_open_1db
  (JNIEnv *, jclass, jstring);

/*
 * Class:     douzi_kaoshi_scpm_jni_DBManagerNative
 * Method:    getSingleChoiceMainQues
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_douzi_kaoshi_scpm_jni_DBManagerNative_getSingleChoiceMainQues
  (JNIEnv *, jclass, jlong);

/*
 * Class:     douzi_kaoshi_scpm_jni_DBManagerNative
 * Method:    getSubChoiceQues
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_douzi_kaoshi_scpm_jni_DBManagerNative_getSubChoiceQues
  (JNIEnv *, jclass, jlong);

/*
 * Class:     douzi_kaoshi_scpm_jni_DBManagerNative
 * Method:    close_db
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_douzi_kaoshi_scpm_jni_DBManagerNative_close_1db
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
